apiVersion: v1
kind: Service
metadata:
  name: openvpn-service
spec:
  type: NodePort
  selector:
    app: openvpn
  ports:
    - protocol: UDP
      port: 1194
      targetPort: 1194
      nodePort: 30443